### ISSUE TITLE
POST http://127.0.0.1:5500/https://www.publicalbum.org/api/v2/webapp/embed-player/jsonrpc 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by dudematthew** [lukascode/photo-gallery#1]
Próbowałem odpalić podany przez Ciebie kod.

Z racji, że sam nie mam proxy, ustawiłem fetch aby posiadał zafiksowane dane, które podałeś w tutorialu.

```
return fetch('https://www.publicalbum.org/api/v2/webapp/embed-player/jsonrpc', {
                method: 'POST',
                body: JSON.stringify(payload),
                headers: {
                    'Content-Type': 'text/plain;charset=UTF-8',
                    'Accept': 'application/json'
                },
                referrer: "https://www.publicalbum.org/blog/embedding-google-photos-albums"
            })
                .then(response => response.json())
                .then(response => response["result"]);
```

Niestety otrzymuję w zwrotce błąd 'bad request'

{id: null, result: null, error: {…}}
error:
code: 0
message: "Bad request."
[[Prototype]]: Object
id: null
result: null
[[Prototype]]: Object

Czego nie wiem o ngixie? Czemu może mi to nie działać? Pomoc byłaby dla mnie zbawieniem.

**Comment by lukascode** [comment]
Hej,

Proxy jest niezbędne gdyż żądanie wyjściowe wychodzi z innej domeny niż publicalbum.org. Gdy wysyłasz żądanie przeglądarka automatycznie doda nagłówek Referer, w którym będzie domena, w kontekście której się znajdujesz np. example.org. Z tego co testowałem serwer pulicalbum.org waliduje ten nagłówek więc po prostu po stronie nginx podmieniłem go w locie ;)

Zerknij na kawałek mojej konfiguracji nginx:

```
location /google-photo-album {
           proxy_set_header        Referer https://www.publicalbum.org/blog/embedding-google-photos-albums;
           proxy_pass              https://www.publicalbum.org/api/v2/webapp/embed-player/jsonrpc;
}

location /gallery {
           root /home/ubuntu/photo-gallery;
           try_files /index.html = 404;
}
```

Z tego co testowałem teraz, wszystko nadal działa: 
https://lsdev.pl/gallery

Prośba o komentarz tutaj https://lsdev.pl/posts/jak-wyswietlic-albumy-z-google-photos-na-swojej-stronie/
jeżeli moja odpowiedź Ciebie satysfakcjonuje ;)

**Comment by dudematthew** [comment]
Dziękuję za odpowiedź! 

Kurczę, miałem nadzieję na używanie API na aplikacji lokalnej, bez backendu :/ 

Da radę samym webpackiem to zrobić?

**Comment by lukascode** [comment]
Myślę, że da się to zrobić. Nie wiem jakich narzędzi używasz natomiast to jest kwestia przestawienia nagłówka w locie np. https://angular.io/guide/build#bypass-the-proxy

Ewentualnie na lokalnym środowisku możesz spróbować skorzystać z mojego proxy tj. https://lsdev.pl/google-photo-album i powinno zadziałać ;)

**Comment by dudematthew** [comment]
Dziękuję bardzo za wskazówki! 

Spróbuję to rozpracować.

**Comment by lukascode** [comment]
W takim razie zamykam issue. Jeżeli będziesz miał jakieś problemy/pytania daj znać pod postem w komentarzu może jeszcze komuś się przyda ;) ewentualnie na maila.
